#!/usr/bin/env python

import numpy as np
import rospy
from Env import Env
import random

class random_agent(object):
    def __init__(self):
		
        self.Env = Env()
	
    def rdn_agent(self):
        self.Env.reset()
        while True:	
    	    a = -0.5
    	    b = -0.5
    	    c = random.random() 
    	    action = [a,b,c]
            self.state,reward,Status,a = self.Env.step(action)
            print(reward)
            print(Status)
            if Status == True:
                self.Env.reset()
				
if __name__ == '__main__':
    rospy.init_node('agent', anonymous=True)
    agt = random_agent()
    agt.rdn_agent()
			
		
